# run with "docker compose up -d"

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./.${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_SCHEMA}
    ports:
      - ${DB_MAPPED_PORT}:5432
